### PR TITLE
Replace deprecated function utf8_encode with mb_convert_encoding.

### PR DESCRIPTION
**Pull request by lukassteiner**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>In php8.2 utf8_encode is deprecated, replaced with mb_convert_encoding </li> 
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

### CODE REVIEW

**Comment by kevinklinke** [comment]
I think you need to run the `composer cs:php:fix` command described in the CONTRIBUTING file, I think it will add a `\` prefix on the method call

**Comment by kevinklinke** [comment]
Do you know what `mbstring.internal_encoding` or `default_charset` is set to? Looks like the method you have assumes the original encoding is whatever that is set to (https://www.php.net/manual/en/function.mb-convert-encoding.php). Alternatively, if we want to carry forward existing logic exactly from `utf8_encode`, we could hard-code the existing encoding as `ISO-8859-1` in the third param (https://www.php.net/manual/en/function.utf8-encode.php)

**Comment by lukassteiner** [comment]
@kevinklinke Thank you for your answer. I fixed these two points.
And I agree that it should be set to `ISO-8859-1 ` to keep the logic the same as it was before.

**Review by kevinklinke — APPROVED** [review]

**Comment by lukassteiner** [comment]
Is there anything I can do to run the checks so that this PR can be merged?

**Comment by kevinklinke** [comment]
> Is there anything I can do to run the checks so that this PR can be merged?

I think @norberttech needs to help with that. I don't have permissions for anything in this repo either :)

**Comment by norberttech** [comment]
@kevinklinke Since I'm currently focused on other projects and I'm not expecting to use App Insights anytime soon, would you maybe like to become a maintainer of app insights PHP repos?

**Comment by lukassteiner** [comment]
Thank you for merging it @norberttech .
It would be helpful for me to have a new tag for this commit so that I can update my composer.json.

**Pull request merged**
