### PR TITLE
Add microseconds to timestamps

### PR DESCRIPTION
**Pull request by kevinklinke**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    <li>Add microseconds to timestamps</li>
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

Currently all timestamps sent by the library are truncated to seconds, so millisecond and microsecond timings are discarded. This makes it much less useful when trying to debug and track events within a single HTTP request.

This is the same issue that is called out on the original repo: https://github.com/microsoft/ApplicationInsights-PHP/issues/72

I also removed the UTC offset since it's not needed since we are using UTC datetimes throughout.

|||
|-|-|
| Example current timestamp | `2023-10-05T06:03:06+00:00Z` |
| Example new timestamp | `2023-10-05T06:03:06.000000Z` |
| Example new timestamp (with microseconds) | `2023-10-05T06:03:06.123456Z` |

### CODE REVIEW

**Comment by kevinklinke** [comment]
@norberttech Can you please help take a look at this PR? I think this is an overall improvement that all consumers would appreciate.

**Comment by norberttech** [comment]
<s>hey @kevinklinke I'm so sorry for missing this one, not sure how it happens, could you please just update the readme description so I can merge it? </s> nvm I updated the description :P

**Comment by kevinklinke** [comment]
@norberttech No problem, I wasn't quite sure of the process so wasn't sure if you'd get notified automatically or not :). I see you've already sort of fixed it, thanks! I was trying to figure out what the required syntax was since the error just says "Invalid Pull Request syntax." but you beat me to it

**Comment by norberttech** [comment]
This repo is using [automation](https://github.com/aeon-php/automation) to generate a changelog, but it requires a pull request description to start with HTML that lists all changes. I simply updated the description and it worked out automatically. Anyway, I just released new version, let me know it that works for you!

**Pull request merged**
